#!/bin/bash

check_format=0
soft_check=0
hard_check=0

while getopts "fF" opt
do
        case $opt in
                (f) check_format=1 ; soft_check=1 ;;
                (F) check_format=1 ; hard_check=1 ;;
                (*) printf "Illegal option '-%s'\n" "$opt" && exit 1 ;;
        esac
        shift
done

# for all files not .in or .out
    # filename=$(basename -- "$file")
    # filename="${filename%.*}"
    # g++ -o $filename $file
    # i = 0
    # for all files of type .in
        # i=$(( i + 1 ))
        #./$filename < $infile > $i.tmp_out
    # cat *.tmp_out > $filename.out
    # kompare $filename.out $sample

for file in "$@"; do
    if [[ $file == *.out ]]; then
        sample=$file
    fi
done

echo
echo "Processing Files..."

for file in "$@"; do
    if [[ $file != *.out ]] && [[ $file != *.in ]]; then
        echo $file
        filename=$(basename -- "$file")
        filename="${filename%.*}"
        g++ -o $filename $file
        i=0
        for in_file in "$@"; do
            if [[ $in_file == *.in ]]; then
                i=$(( i + 1 ))
                ./$filename < $in_file > $i.tmp_out
            fi
        done
        cat *.tmp_out > $filename.out
        rm *.tmp_out
        kompare $filename.out sample.out
    fi
done

if [[ $check_format -eq 1 ]]; then
    echo ""
    echo ""
    echo "List of students who did not use Astyle:"
    
    for file in "$@"; do
        if [[ $file != *.out ]] && [[ $file != *.in ]]; then
            filename=$(basename -- "$file")
            extension="${filename##*.}"
            filename="${filename%.*}"
            astyle < $file > $filename.formatted
            if [[ $soft_check -eq 1 ]]; then
                DIFF=$(diff -b $file $filename.formatted)
            elif [[ $hard_check -eq 1 ]]; then
                DIFF=$(diff $file $filename.formatted)
            fi
            if [ "$DIFF" != "" ]
            then
                echo $filename
            fi
        fi
    done
fi

