#!/bin/bash

check_format=0
soft_check=0
hard_check=0

while getopts "fF" opt
do
        case $opt in
                (f) check_format=1 ; soft_check=1 ;;
                (F) check_format=1 ; hard_check=1 ;;
                (*) printf "Illegal option '-%s'\n" "$opt" && exit 1 ;;
        esac
        shift
done

input="$1"
shift

sample="$1"
shift

for file in "$@"; do
        filename=$(basename -- "$file")
        extension="${filename##*.}"
        filename="${filename%.*}"
        g++ -o $filename $file
        ./$filename < $input > $filename.txt
        kompare $filename.txt $sample
done

if [[ $check_format -eq 1 ]]; then
    echo ""
    echo ""
    echo "List of students who did not use Astyle:"
    
    for file in "$@"; do
            filename=$(basename -- "$file")
            extension="${filename##*.}"
            filename="${filename%.*}"
            astyle < $file > $filename.formatted
            if [[ $soft_check -eq 1 ]]; then
                DIFF=$(diff -b $file $filename.formatted)
            elif [[ $hard_check -eq 1 ]]; then
                DIFF=$(diff $file $filename.formatted)
            fi
            if [ "$DIFF" != "" ]
            then
                    echo $filename
            fi
    done
fi

